services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - $HOME/.local:/home/coder/.local
      - $HOME/.config:/home/coder/.config
      - $PWD:/home/coder/project
    user: "${UID}:${GID}"
    environment:
      - DOCKER_USER=${USER}
    stdin_open: true
    tty: true
    restart: unless-stopped
