---
services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9091:9091"
    volumes:
      - ./config:/config:ro
    environment:
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/session_secret
    secrets:
      - session_secret
    networks:
      - net

networks:
  net:

secrets:
  session_secret:
    file: ./secrets/session_secret
